name: dragon workflow

on: push

jobs:
    my_first_job1:
        runs-on: ubuntu-latest
        steps:
        -   name: install
            run: sudo apt-get install cowsay -y

        -   name: execute
            run: cowsay -f dragon "run dragon " >> dragon.txt

        -   name: sleep
            run: sleep 30

    test_job:
        needs: my_first_job1
        runs-on: ubuntu-latest
        steps:
        -   name: sleep
            run: sleep 10

        -   name: test
            run: grap -i "dragon" dragon.txt

    deploy_job:
        needs: [my_first_job1, test_job]
        runs-on: ubuntu-latest
        steps:
        -   name: check
            run: cat dragon.txt