name: dragon workflow

on: push

jobs:
    my_first_job1:
        runs-on: ubuntu-latest
        steps:
        -   name: install
            run: sudo apt-get install cowsay -y

        -   name: execute
            run: cowsay -f dragon "run dragon " >> dragon.txt


        - uses: actions/upload-artifact@v4
          name: upload artefact
          with:
            name: dragon
            path: dragon.txt

    test_job:
        needs: my_first_job1
        runs-on: ubuntu-latest
        steps:
        - uses: actions/download-artifact@v4
          name: download artefact
          with:
            name: dragon

        -   name: test
            run: grep -i "dragon" dragon.txt


    deploy_job:
        needs: [my_first_job1, test_job]
        runs-on: ubuntu-latest
        steps:
        - uses: actions/download-artifact@v4
          name: download artefact
          with:
            name: dragon

        -   name: check
            run: cat dragon.txt
    